default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5437
  username: kinjaziss
  password: kinjaziss
  pool: 5

development:
  <<: *default
  database: basket_team

test:
  <<: *default
  database: basket_team

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DATABASE", nil) %>
  host: <%= ENV.fetch("DATABASE_HOST", nil) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", nil) %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>
  port: <%= ENV.fetch("DATABASE_PORT", nil) %>